### ISSUE TITLE
Embrace JSON-LD

### ISSUE THREAD

**Issue by asbjornu** [kevinswiber/siren#58]
I think it is inevitable that [JSON-LD](http://json-ld.org/) paves its way through the current quagmire of formats and establishes itself as the only relevant (and true; [it's ratified in W3C](http://www.w3.org/TR/json-ld/)) standard for linking within and between JSON documents (read "resources" if you're picky about it). So however bad anyone feels it is (I quite like it, but nonetheless), I think it's going to be hard to ignore it.

I also feel that JSON-LD requires a very light change to most existing JSON documents, however they are specified (in Siren, JSON API, API Blueprint, etc.) in order to make the documents JSON-LD compatible. Just replace identifying URI property names with `@id` and you're set. Basically.

So, I'm wondering, has any steps, thoughts or anything else been spent or done to make Siren JSON-LD compatible?

**Comment by kevinswiber** [comment]
Thank you for your suggestion.  Siren will not be JSON-LD compatible at this time.  If you're looking for hypermedia controls on top of JSON-LD, I'd like to recommend [Hydra](https://github.com/lanthaler/Hydra) by @lanthaler.

Cheers.

**Comment by asbjornu** [comment]
Thanks for the quick reply! I know about Hydra, but feel Siren is more mature and has more widespread use, which is why I'd like to use it in a new, large project.

But I also think JSON-LD is so valuable that I find myself in a little pickle and don't know how to compromise.

So yea. Back to the drawing board.

**Comment by apsoto** [comment]
IMO, the spec is influenced by real world implementations.  If you find siren and json-ld valuable, it would best help siren if you do an implementation and report back your findings, what worked, what didn't, etc.

**Comment by xogeny** [comment]
A few comments here.  First, it is now 2018 and, as far as I’m concerned, Siren is still better suited for my use cases than JSON-LD (not a knock against JSON-LD, just an observation).  However, I do find the curation or schemas on scheme.org quite interesting.  It would be very cool to be able to somehow tie these together with Siren classes.  The big problem, as far as I can tell, is that I don’t see an obvious way to transform the various “semantic web” formats used on scheme.org into something like JSON scheme so that validation would be possible.
